{
 "title": "Brokers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "artemis_messages_acknowledged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(artemis_messages_acknowledged[$__rate_interval])"
    }
   ]
  },
  {
   "title": "artemis_messages_added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "artemis_messages_added" }
   ]
  },
  {
   "title": "artemis_delivering_message_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "artemis_delivering_message_count{address=\"myIOT\"}"
    }
   ]
  },
  {
   "title": "Address size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "artemis_address_size" }
   ]
  },
  {
   "title": "artemis_message_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "artemis_message_count" }
   ]
  }
 ]
}